### ISSUE TITLE
servicenow.limit properties 

### ISSUE THREAD

**Issue by Airey001** [gflewis/sndml#3]
Use of servicenow.limit properties causes incomplete date retrieval.

With servicenow.limit=500 set the is resulting with following command
load sys_choice truncate

09:24:31 [main] INFO Datamart.DatabaseTableWriter.sys_choice truncate table dbo.sys_choice
09:24:32 [main] INFO ServiceNow.Response.sys_choice getAllKeys 4241 keys (total)
09:24:33 [main] INFO Datamart.JobController.sys_choice 250 of 4241 records processed
09:24:34 [main] INFO Datamart.JobController.sys_choice 500 of 4241 records processed
09:24:36 [main] INFO Datamart.JobController.sys_choice 750 of 4241 records processed
09:24:37 [main] INFO Datamart.JobController.sys_choice 1000 of 4241 records processed
09:24:38 [main] INFO Datamart.JobController.sys_choice 1250 of 4241 records processed
09:24:40 [main] INFO Datamart.JobController.sys_choice 1500 of 4241 records processed
09:24:41 [main] INFO Datamart.JobController.sys_choice 1750 of 4241 records processed
09:24:41 [main] INFO Datamart.JobController.sys_choice 2000 of 4241 records processed
09:24:42 [main] INFO Datamart.JobController.sys_choice 2241 of 4241 records processed
09:24:42 [main] INFO Datamart.Loader Done

As you can see its maxing out at only 250 not 500 as set and losing 2000 rows of records.  This as of the released version 2.6.5 using MSSQL.

**Comment by gflewis** [comment]
Set the system property **glide.remote_glide_record.max_count** in your ServiceNow instance to 500 or a larger value. It should fix your problem.
