### ISSUE TITLE
Wiki edit: Permissions when using a non admin account

### ISSUE THREAD

**Issue by cruscio** [gflewis/sndml#6]
Using a non admin account - https://github.com/gflewis/sndml/wiki/Using-a-non-admin-account

> Certain older versions of ServiceNow contain a defect which causes `sys_dictionary.glide_internal_type` to not be returned in Direct Web Services calls, even if access controls have been created to grant the necessary access. The workaround is to use an account with admin role.

We ran into this on Jakarta (not an older version) and found an alternative that didn't require full admin access: https://community.servicenow.com/thread/191960

> Correct Answer: Type is a reference of the table 'sys_glide_object'.  Maybe you need a read on that table to see the values

Just wanted to let you know in case it was worth adding to the wiki.

**Comment by gflewis** [comment]
Wiki page updated. Thanks.
