### ISSUE TITLE
Oracle Column name limit 3o char

### ISSUE THREAD

**Issue by khopala** [gflewis/sndml#7]
I have found another issue. with Oracle Column name limit 30 char. Getting error while creating table(incident) in Oracle. It seems user defined column in Servicenow.

**Comment by gflewis** [comment]
If you have ServiceNow column names longer than the Oracle limit, you will need to create a Field Name Map.  This allows you to "rename" a column. First generate a list of all the fields whose names are too long, and decide what the new (shorter) name should be. Make a copy of the file **src/main/resources/sqltemplates.xml**.  The Field Name Map looks like this:

    <fieldnames>
      <namemap glidename="u_field_name1">oracle_name1</namemap>
      <namemap glidename="u_field_name2">oracle_name2</namemap>
    </fieldnames>

You can use a property to point to the loader to your new templates file as follows (this property was added in 2.6.6)

    datamart.templates=my_templates_file.xml

Let me know if this works for you.

**Comment by khopala** [comment]
Awesome. it has worked. Thank you much!
