### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by khopala** [gflewis/sndml#9]
10:21:35 [main] INFO Datamart.DatabaseWriter schema=SERVICENOW
10:21:35 [main] INFO Datamart.DatabaseWriter timezoneName=Greenwich Mean Time
10:21:35 [main] INFO Datamart.DatabaseWriter autocreate=true
10:21:35 [main] INFO Datamart.DatabaseWriter batch_inserts=false
10:21:35 [main] INFO Datamart.DatabaseWriter alter session set nls_length_semantics = 'CHAR'
10:21:35 [main] INFO Datamart.DatabaseWriter alter session set nls_date_format = 'YYYY-MM-DD'
10:21:35 [main] INFO Datamart.DatabaseWriter alter session set nls_timestamp_format = 'YYYY-MM-DD HH24:MI:SS'
10:21:35 [main] INFO Datamart.DatabaseWriter alter session set time_zone = '+0:00'
10:22:35 [main] WARN ServiceNow.Response.task Transaction cancelled: SOAPProcessorThreadf7dcfc1e13bb874012c2bc122244b069: redirect count exceeded or request did not finish within 60 seconds - terminating request...
10:22:35 [main] ERROR ServiceNow.Response.task responseCode=500 Internal Server Error
Transaction cancelled: SOAPProcessorThreadf7dcfc1e13bb874012c2bc122244b069: redirect count exceeded or request did not finish within 60 seconds - terminating request...
Exception in thread "main" servicenow.common.datamart.SuiteExecException: servicenow.common.soap.SoapResponseException: responseCode=500 Internal Server Error
table=task
Transaction cancelled: SOAPProcessorThreadf7dcfc1e13bb874012c2bc122244b069: redirect count exceeded or request did not finish within 60 seconds - terminating request...
        at servicenow.common.datamart.JobController.runJob(JobController.java:183)
        at servicenow.common.datamart.SuiteController.runOnce(SuiteController.java:229)
        at servicenow.common.datamart.Loader.runToComplete(Loader.java:228)
        at servicenow.common.datamart.Loader.main(Loader.java:91)
Caused by: servicenow.common.soap.SoapResponseException: responseCode=500 Internal Server Error
table=task
Transaction cancelled: SOAPProcessorThreadf7dcfc1e13bb874012c2bc122244b069: redirect count exceeded or request did not finish within 60 seconds - terminating request...
        at servicenow.common.soap.TableProxy.callSoap(TableProxy.java:161)
        at servicenow.common.soap.Table.getKeys(Table.java:605)
        at servicenow.common.soap.KeyReader.nextKeyChunk(KeyReader.java:62)
        at servicenow.common.soap.KeyReader.getAllKeys(KeyReader.java:86)
        at servicenow.common.soap.BasicTableReader.getKeys(BasicTableReader.java:149)
        at servicenow.common.datamart.JobController.runLoad(JobController.java:223)
        at servicenow.common.datamart.JobController.runJob(JobController.java:141)
        ... 3 more
10:22:35 [Thread-0] INFO Datamart.ShutdownHook ShutdownHook invoked
10:22:35 [Thread-0] INFO Datamart.ShutdownHook ShutdownHook complete

**Comment by gflewis** [comment]
Can you give me some more information about the conditions in which this error occurred? Which table are you accessing? Have you successfully loaded other tables from the same instance? Have you successfully loaded this table before? Is the error reproducible? Thanks.

**Comment by khopala** [comment]
Getting error while loading c_req_item and task tables. We are loading these tables very first time. Not seeing issue with other tables. Thank you for all your support!

**Comment by gflewis** [comment]
What is the total number of rows in each of these tables? How many rows are you attempting to load? Are you attempting to load all of the rows at once? It looks like you might be getting a timeout error when it is calling "getKeys".

**Comment by gflewis** [comment]
Try loading a subset of the records. For example, use this command to load only records created in December 2017.  If the subset works, but the full load does not, then it is probably a timeout error.

    load task created from 2017-12-01 to 2018-01-01

**Comment by khopala** [comment]
Yes, we attempt to load all rows. I have not checked total rows. 
I am going to try limiting row parmeter and see how it works. I will also try subset as well that you mentioned above.

servicenow.limit= 200000
servicenow.task.limit=200000
servicenow.c_req_item=200000
servicenow.getkeys_limit=200000

**Comment by gflewis** [comment]
You will certainly get a timeout error if you set **servicenow.task.limit** to **200000**.  The default is **200**.  I have never set this parameter higher than **500**.  You might also want to try setting **servicenow.getkeys_limit** to a lower number such as **50000**.  Higher numbers can improve performance, but they also increase the likelihood of a timeout error.

**Comment by khopala** [comment]
You are correct, got same error. I changed parameter to1000 and it has worked. Awesome :) Once again Thank you so much for all your help and support!
